name: daily-cron
on:
  push:
    branches:
      - main
  schedule:
    - cron: '00 21 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: node post-daily.mjs
        env:
          AOC_URL: ${{ secrets.AOC_URL }}
          AOC_COOKIE: ${{ secrets.AOC_COOKIE }}
          SLACK_HOOK: ${{ secrets.SLACK_HOOK }}
